Repository Han-Zan/HanZan_Android, pull requests merged in 2022-11, with the labels that each got.

#26 [Fix] 레트로핏 토큰 처리
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/HanZanApplication.kt
  app/src/main/java/com/kud/hanzan/adapter/DrinkRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/HomeAlcoholRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/camera/CameraResultItemRVAdapter.kt
  app/src/main/java/com/kud/hanzan/di/NetworkModule.kt
  app/src/main/java/com/kud/hanzan/di/ServiceModule.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkListFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkListViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/dialog/ConfirmDialog.kt
  app/src/main/java/com/kud/hanzan/ui/dialog/ImageSelectDialog.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeActivity.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeAlcoholFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeCombFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreFragment.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/title/TitleActivity.kt
  app/src/main/java/com/kud/hanzan/utils/AuthInterceptor.kt
  app/src/main/java/com/kud/hanzan/vision/BaseImageAnalyzer.kt
  app/src/main/java/com/kud/hanzan/vision/GraphicOverlay.kt
  app/src/main/java/com/kud/hanzan/vision/TextRecognitionGraphic.kt
  app/src/main/java/com/kud/hanzan/vision/TextRecognitionProcessor.kt
  app/src/main/java/com/kud/hanzan/vision/TextSimilarityChecker.kt
  app/src/main/res/drawable/bg_black_dialog.xml
  app/src/main/res/layout/activity_camera_result.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/layout/dialog_image_select.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/layout/item_drink.xml
  app/src/main/res/layout/item_home_alcohol.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kud/hanzan/data/remote/HanzanLoginService.kt
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRepositoryImpl.kt
  data/src/main/java/com/kud/hanzan/data/source/login/LoginDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/Drink.kt
  domain/src/main/java/com/kud/hanzan/domain/model/map/StoreDetail.kt
Labels: update

#28 [FIX] 한잔 API KEY 숨기기
  app/build.gradle
  app/src/main/java/com/kud/hanzan/HanZanApplication.kt
  app/src/main/java/com/kud/hanzan/adapter/camera/CameraResultItemRVAdapter.kt
  app/src/main/java/com/kud/hanzan/di/AwsModule.kt
  app/src/main/java/com/kud/hanzan/di/NetworkModule.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkListFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkListViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeActivity.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapFragment.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreFragment.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreViewModel.kt
  app/src/main/java/com/kud/hanzan/utils/URIPathHelper.kt
  app/src/main/java/com/kud/hanzan/utils/Utils.kt
  app/src/main/res/layout/fragment_map.xml
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/CombinationRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/combination/GetDrinkListUseCase.kt
Labels: update

#29 Revert "[FIX] 한잔 API KEY 숨기기"
  app/build.gradle
  app/src/main/java/com/kud/hanzan/HanZanApplication.kt
  app/src/main/java/com/kud/hanzan/adapter/camera/CameraResultItemRVAdapter.kt
  app/src/main/java/com/kud/hanzan/di/AwsModule.kt
  app/src/main/java/com/kud/hanzan/di/NetworkModule.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkListFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkListViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeActivity.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapFragment.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreFragment.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreViewModel.kt
  app/src/main/java/com/kud/hanzan/utils/URIPathHelper.kt
  app/src/main/java/com/kud/hanzan/utils/Utils.kt
  app/src/main/res/layout/fragment_map.xml
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/CombinationRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/combination/GetDrinkListUseCase.kt
Labels: bug

#32 [IMPL] 술BTI 구현 완료 및 안주 리스트 구현 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/adapter/FoodRVAdapter.kt
  app/src/main/java/com/kud/hanzan/di/RepositoryModule.kt
  app/src/main/java/com/kud/hanzan/ui/combination/CombinationFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/FoodCategoryFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/FoodListFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/FoodListViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/profile/ProfileFragment.kt
  app/src/main/java/com/kud/hanzan/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiResultActivity.kt
  app/src/main/res/drawable/ic_food_dessert.png
  app/src/main/res/drawable/ic_food_dry.png
  app/src/main/res/drawable/ic_food_etc.png
  app/src/main/res/drawable/ic_food_fish.png
  app/src/main/res/drawable/ic_food_fries.png
  app/src/main/res/drawable/ic_food_fruit.png
  app/src/main/res/drawable/ic_food_meat.png
  app/src/main/res/drawable/ic_food_soup.png
  app/src/main/res/drawable/src_sbti_challenge.png
  app/src/main/res/drawable/src_sbti_home.png
  app/src/main/res/drawable/src_sbti_misik.png
  app/src/main/res/drawable/src_sbti_only_drink.png
  app/src/main/res/drawable/src_sbti_party.png
  app/src/main/res/layout/activity_sbti_result.xml
  app/src/main/res/layout/fragment_drink_list.xml
  app/src/main/res/layout/fragment_food_category.xml
  app/src/main/res/layout/fragment_food_list.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_food.xml
  app/src/main/res/navigation/main_bottom_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRepositoryImpl.kt
  data/src/main/java/com/kud/hanzan/data/source/login/LoginDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/profile/ProfileDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/profile/ProfileRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/Food.kt
  domain/src/main/java/com/kud/hanzan/domain/model/User.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/CombinationRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/ProfileRepository.kt
Labels: enhancement

#33 [Impl] OCR 자연어 처리 서버 연동
  app/src/main/java/com/kud/hanzan/adapter/camera/CameraResultItemRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/camera/CameraResultVPAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/map/MapStoreRVAdapter.kt
  app/src/main/java/com/kud/hanzan/di/RepositoryModule.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraDrinkFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFoodFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapFragment.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreFragment.kt
  app/src/main/res/drawable/bg_progress_camera_result.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/activity_camera_result.xml
  app/src/main/res/layout/fragment_camera.xml
  app/src/main/res/layout/fragment_camera_drink.xml
  app/src/main/res/layout/fragment_camera_food.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_camera_result.xml
  app/src/main/res/layout/item_custom_balloon.xml
  app/src/main/res/layout/item_home_comb.xml
  app/src/main/res/layout/item_map_store.xml
  app/src/main/res/navigation/main_bottom_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kud/hanzan/data/entity/camera/CamPostDto.kt
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraRepositoryImpl.kt
  data/src/main/java/com/kud/hanzan/data/source/kakao/KakaoRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/map/Store.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/CameraRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/KakaoRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/camera/PostCameraDrinkUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/camera/PostCameraFoodUseCase.kt
Labels: update

#34 [FIX] FoodCategoryFragment layout fixed
  app/src/main/java/com/kud/hanzan/ui/combination/FoodCategoryFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/FoodListFragment.kt
  app/src/main/res/layout/fragment_food_category.xml
  app/src/main/res/layout/item_food.xml
Labels: enhancement, update

#35 [IMPL] 사용자 닉네임 및 프로필사진 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/ui/dialog/OneEditTextDialog.kt
  app/src/main/java/com/kud/hanzan/ui/profile/ProfileFragment.kt
  app/src/main/java/com/kud/hanzan/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/title/TitleActivity.kt
  app/src/main/res/layout/activity_title.xml
  app/src/main/res/layout/dialog_image_select.xml
  app/src/main/res/layout/dialog_one_edit_text.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kud/hanzan/data/source/profile/ProfileDataSource.kt
Labels: enhancement

#36 [Impl] 술 선택 추가
  .firebaserc
  app/build.gradle
  app/src/main/java/com/kud/hanzan/adapter/DrinkRVAdapter.kt
  app/src/main/java/com/kud/hanzan/di/RepositoryModule.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/combination/CombinationFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkListFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeAlcoholFragment.kt
  app/src/main/res/drawable/bg_cardview_check.xml
  app/src/main/res/layout/fragment_camera.xml
  app/src/main/res/layout/fragment_combination.xml
  app/src/main/res/layout/fragment_drink.xml
  app/src/main/res/layout/item_property_indicator.xml
  app/src/main/res/navigation/main_bottom_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/drink/DrinkDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/drink/DrinkRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/drink/DrinkRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/DrinkDetail.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/DrinkRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/drink/GetDrinkUseCase.kt
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
Labels: enhancement

#39 [IMPL] 술BTI 재확인 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/ui/MainActivity.kt
  app/src/main/java/com/kud/hanzan/ui/combination/CombinationFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/CombinationViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeActivity.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiCheckActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiResultActivity.kt
  app/src/main/res/layout/activity_sbti_check.xml
  app/src/main/res/layout/fragment_combination.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/combination/CombinationRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/Comb.kt
  domain/src/main/java/com/kud/hanzan/domain/model/Food.kt
  domain/src/main/java/com/kud/hanzan/domain/model/HomeData.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/CombinationRepository.kt
Labels: enhancement

#41 [Impl] 브로드캐스트 푸시 알림 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/HanZanApplication.kt
  app/src/main/java/com/kud/hanzan/notification/AlarmReceiver.kt
  app/src/main/java/com/kud/hanzan/notification/MyFirebaseMessagingService.kt
  app/src/main/java/com/kud/hanzan/notification/RatingActivity.kt
  app/src/main/java/com/kud/hanzan/ui/dialog/BottomSheet.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeActivity.kt
  app/src/main/java/com/kud/hanzan/utils/base/BaseActivity.kt
  app/src/main/res/layout/activity_rating.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  data/build.gradle
  domain/build.gradle
Labels: enhancement

#44 [Impl] 가게 화면 메뉴 이미지 서버 연동
  app/src/main/java/com/kud/hanzan/adapter/store/StoreMenuImageRVAdapter.kt
  app/src/main/java/com/kud/hanzan/di/RepositoryModule.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapFragment.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreFragment.kt
  app/src/main/java/com/kud/hanzan/ui/map/StoreViewModel.kt
  app/src/main/res/layout/dialog_image_select.xml
  app/src/main/res/layout/fragment_drink.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/layout/item_store_menu_image.xml
  build.gradle
  data/build.gradle
  data/src/main/java/com/kud/hanzan/data/entity/store/StoreKakaoData.kt
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/store/StoreDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/store/StoreRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/store/StoreRepositoryImpl.kt
  domain/build.gradle
  domain/src/main/java/com/kud/hanzan/domain/model/DrinkDetail.kt
  domain/src/main/java/com/kud/hanzan/domain/model/map/StoreCombData.kt
  domain/src/main/java/com/kud/hanzan/domain/model/map/StoreDetail.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/StoreRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/store/GetStoreUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/store/PostStoreUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/store/PutStoreImageUseCase.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, enhancement

#45 [IMPL] 술BTI 결과 카카오톡 공유
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiCheckActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiResultActivity.kt
  app/src/main/res/layout/activity_sbti_check.xml
  app/src/main/res/layout/activity_sbti_result.xml
Labels: enhancement

#46 [FIX] 카메라 화면 및 좋아요 화면 오류 수정
  app/src/main/java/com/kud/hanzan/adapter/DrinkRVAdapter.kt
  app/src/main/java/com/kud/hanzan/ui/MainActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraDrinkFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFoodFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/combination/DrinkFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeAlcoholFragment.kt
  app/src/main/java/com/kud/hanzan/ui/search/SearchActivity.kt
  app/src/main/res/navigation/main_bottom_graph.xml
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/LikeDrink.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/PreferredRepository.kt
Labels: update

#47 [IMPL] 술 & 안주 직접 입력하기
  app/src/main/java/com/kud/hanzan/adapter/camera/CameraResultItemRVAdapter.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraDrinkFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFoodFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/combination/FoodListFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/FoodListViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/profile/ProfileFragment.kt
  app/src/main/java/com/kud/hanzan/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/ranking/RankingFragment.kt
  app/src/main/java/com/kud/hanzan/ui/ranking/RankingViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/title/TitleActivity.kt
  app/src/main/res/layout/fragment_camera_drink.xml
  app/src/main/res/layout/fragment_camera_food.xml
  app/src/main/res/layout/fragment_food_list.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_ranking.xml
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/CameraRepository.kt
Labels: enhancement

#48 [ADD] 알림 연동 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/adapter/camera/CameraResultCombRVAdapter.kt
  app/src/main/java/com/kud/hanzan/notification/AlarmReceiver.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraCombActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraCombViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeActivity.kt
  app/src/main/res/layout/activity_camera_comb.xml
  app/src/main/res/layout/item_camera_comb_layout.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/kud/hanzan/domain/model/CombinationInfo.kt
Labels: enhancement

#50 [UPD] 알림 오류 수정 및 데이터 연동
  app/src/main/java/com/kud/hanzan/notification/AlarmReceiver.kt
  app/src/main/java/com/kud/hanzan/notification/RatingActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraCombActivity.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeActivity.kt
  app/src/main/res/layout/activity_rating.xml
Labels: bug

#51 [IMPL] 프로필 사진 변경시 S3 버킷에 업로드
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/ui/dialog/ImageSelectDialog.kt
  app/src/main/java/com/kud/hanzan/ui/profile/ProfileFragment.kt
  app/src/main/java/com/kud/hanzan/ui/profile/ProfileViewModel.kt
  app/src/main/res/layout/dialog_image_select.xml
Labels: enhancement

#52 [Impl] 알림 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/adapter/camera/CameraResultCombRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/like/LikeCombRVAdapter.kt
  app/src/main/java/com/kud/hanzan/di/RepositoryModule.kt
  app/src/main/java/com/kud/hanzan/notification/AlarmReceiver.kt
  app/src/main/java/com/kud/hanzan/notification/RatingActivity.kt
  app/src/main/java/com/kud/hanzan/notification/RatingViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraCombActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraCombViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeCombFragment.kt
  app/src/main/res/layout/activity_camera_comb.xml
  app/src/main/res/layout/activity_rating.xml
  app/src/main/res/layout/item_camera_comb_layout.xml
  app/src/main/res/layout/item_like_comb.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kud/hanzan/data/entity/rating/RatingDto.kt
  data/src/main/java/com/kud/hanzan/data/entity/recommend/RecommandationDto.kt
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/camera/CameraRepositoryImpl.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRepositoryImpl.kt
  data/src/main/java/com/kud/hanzan/data/source/rating/RatingDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/rating/RatingRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/rating/RatingRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/Combination.kt
  domain/src/main/java/com/kud/hanzan/domain/model/RecommendItem.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/CameraRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/RatingRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/camera/GetRecommendUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/rating/PostRatingUseCase.kt
Labels: update
