Repository Han-Zan/HanZan_Android, pull requests merged in 2022-10, with the labels that each got.

#8 [ADD] 카테고리 화면
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/adapter/category/CategoryMainRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/category/CategoryPopularRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/category/CategorySubRVAdapter.kt
  app/src/main/java/com/kud/hanzan/ui/category/CategoryFragment.kt
  app/src/main/res/drawable/bg_white_button_test.xml
  app/src/main/res/drawable/bg_yellow_button_test.xml
  app/src/main/res/drawable/cb_map_category_selector.xml
  app/src/main/res/drawable/color_category_btn.xml
  app/src/main/res/drawable/color_category_tv.xml
  app/src/main/res/drawable/ic_search_colored.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_main_category.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/layout/item_sub_category.xml
  app/src/main/res/navigation/main_bottom_graph.xml
  app/src/main/res/values/array.xml
  domain/src/main/java/com/kud/hanzan/domain/model/Category.kt
Labels: enhancement

#9 [Impl] 술BTI & 술BTI 결과 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/ui/login/LoginActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiFragment.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiProgressBarFragment.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiTipsFragment.kt
  app/src/main/res/drawable/sbti_type_lonely_gourmet.png
  app/src/main/res/layout/activity_sbti.xml
  app/src/main/res/layout/activity_sbti_result.xml
  app/src/main/res/layout/fragment_sbti.xml
  app/src/main/res/layout/fragment_sbti_progress_bar.xml
  app/src/main/res/layout/fragment_sbti_tips.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#10 [ADD] 메인 화면 하단바 변경 및 카메라 화면 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/adapter/like/LikeAlcoholRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/like/LikeVPAdapter.kt
  app/src/main/java/com/kud/hanzan/ui/MainActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraActivity.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikePreferredFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeRecentFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeViewModel.kt
  app/src/main/java/com/kud/hanzan/vision/BaseImageAnalyzer.kt
  app/src/main/java/com/kud/hanzan/vision/GraphicOverlay.kt
  app/src/main/java/com/kud/hanzan/vision/TextRecognitionGraphic.kt
  app/src/main/java/com/kud/hanzan/vision/TextRecognitionProcessor.kt
  app/src/main/res/drawable/cb_heart_selector.xml
  app/src/main/res/drawable/ic_camera_turn.png
  app/src/main/res/drawable/ic_heart_selected.xml
  app/src/main/res/drawable/ic_heart_unselected.xml
  app/src/main/res/drawable/ic_sort.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_like_preferred.xml
  app/src/main/res/layout/fragment_like_recent.xml
  app/src/main/res/layout/item_like_alcohol.xml
  app/src/main/res/layout/item_sub_category.xml
  app/src/main/res/layout/list_popup_like_sort.xml
  app/src/main/res/menu/menu_default.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/main_bottom_graph.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: update

#11 [Impl] Kakao Login & Data intent
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/ui/login/LoginActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/search/SearchActivity.kt
  app/src/main/java/com/kud/hanzan/ui/title/TitleActivity.kt
  app/src/main/res/drawable-v24/bg_neon_sign.png
  app/src/main/res/drawable-v24/kakao_login_large_wide.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sbti_result.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/activity_title.xml
Labels: enhancement

#12 [ADD] 찜 조합 API 연결 및 파이어베이스 연동
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/HanZanApplication.kt
  app/src/main/java/com/kud/hanzan/adapter/like/LikeVPAdapter.kt
  app/src/main/java/com/kud/hanzan/di/NetworkModule.kt
  app/src/main/java/com/kud/hanzan/di/RepositoryModule.kt
  app/src/main/java/com/kud/hanzan/di/ServiceModule.kt
  app/src/main/java/com/kud/hanzan/notification/MyFirebaseMessagingService.kt
  app/src/main/java/com/kud/hanzan/ui/MainActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraActivity.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeAlcoholFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeCombFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeRecentFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapViewModel.kt
  app/src/main/java/com/kud/hanzan/utils/Utils.kt
  app/src/main/res/layout/fragment_like_alcohol.xml
  app/src/main/res/layout/fragment_like_combination.xml
  app/src/main/res/layout/fragment_like_recent.xml
  app/src/main/res/values/strings.xml
  build.gradle
  data/src/main/java/com/kud/hanzan/data/entity/preferred/CombResult.kt
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/kakao/KakaoDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/kakao/KakaoRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/kakao/KakaoRepositoryImpl.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/Combination.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/PreferredRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/kakao/GetKeywordPlaceUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/kakao/GetRoadAddressUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/preferred/GetPreferredCombUseCase.kt
Labels: enhancement

#15 [FIX] Drawable Merge Conflict
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/fragment_camera.xml
  app/src/main/res/layout/fragment_camera_result.xml
  app/src/main/res/layout/fragment_like_alcohol.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_camera_result.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: bug

#16 [Impl] SbtiViewModel
  app/src/main/java/com/kud/hanzan/di/RepositoryModule.kt
  app/src/main/java/com/kud/hanzan/ui/login/LoginActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/sbti/SbtiResultViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/title/TitleActivity.kt
  app/src/main/res/layout/activity_sbti_result.xml
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/login/LoginDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/login/LoginRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/UserInfo.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/LoginRepository.kt
Labels: enhancement

#17 [UPD] 홈화면 수정 및 좋아요 화면 API 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kud/hanzan/adapter/HomeAlcoholRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/like/LikeAlcoholRVAdapter.kt
  app/src/main/java/com/kud/hanzan/adapter/like/LikeCombRVAdapter.kt
  app/src/main/java/com/kud/hanzan/ui/MainActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraActivity.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraFragment.kt
  app/src/main/java/com/kud/hanzan/ui/camera/CameraResultActivity.kt
  app/src/main/java/com/kud/hanzan/ui/category/CategoryFragment.kt
  app/src/main/java/com/kud/hanzan/ui/combination/CombinationFragment.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeActivity.kt
  app/src/main/java/com/kud/hanzan/ui/home/HomeFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeAlcoholFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeCombFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeFragment.kt
  app/src/main/java/com/kud/hanzan/ui/like/LikeViewModel.kt
  app/src/main/java/com/kud/hanzan/ui/map/MapFragment.kt
  app/src/main/java/com/kud/hanzan/ui/title/TitleActivity.kt
  app/src/main/res/drawable/bg_like_comb.xml
  app/src/main/res/drawable/ic_combination.xml
  app/src/main/res/drawable/ic_next_profile.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/activity_camera_result.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_camera.xml
  app/src/main/res/layout/fragment_combination.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_like_alcohol.xml
  app/src/main/res/layout/fragment_like_combination.xml
  app/src/main/res/layout/item_home_alcohol.xml
  app/src/main/res/layout/item_like_alcohol.xml
  app/src/main/res/layout/item_like_comb.xml
  app/src/main/res/layout/list_popup_like_sort.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/menu/toolbar_search.xml
  app/src/main/res/navigation/camera_graph.xml
  app/src/main/res/navigation/main_bottom_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kud/hanzan/data/entity/Drink.kt
  data/src/main/java/com/kud/hanzan/data/entity/preferred/CombResult.kt
  data/src/main/java/com/kud/hanzan/data/entity/preferred/DrinkResult.kt
  data/src/main/java/com/kud/hanzan/data/entity/preferred/PreferredCombDto.kt
  data/src/main/java/com/kud/hanzan/data/entity/preferred/PreferredDrinkDto.kt
  data/src/main/java/com/kud/hanzan/data/remote/HanzanService.kt
  data/src/main/java/com/kud/hanzan/data/source/login/LoginDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRemoteDataSource.kt
  data/src/main/java/com/kud/hanzan/data/source/preferred/PreferredRepositoryImpl.kt
  domain/src/main/java/com/kud/hanzan/domain/model/Alcohol.kt
  domain/src/main/java/com/kud/hanzan/domain/model/Combination.kt
  domain/src/main/java/com/kud/hanzan/domain/model/LikeAlcohol.kt
  domain/src/main/java/com/kud/hanzan/domain/repository/PreferredRepository.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/preferred/DeletePreferredCombUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/preferred/DeletePreferredDrinkUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/preferred/GetPreferredDrinkUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/preferred/PostPreferredCombUseCase.kt
  domain/src/main/java/com/kud/hanzan/domain/usecase/preferred/PostPreferredDrinkUseCase.kt
Labels: enhancement, update
